# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_course_add.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_course_add(object):
    def setupUi(self, course_add):
        course_add.setObjectName("course_add")
        course_add.resize(534, 453)
        course_add.setMinimumSize(QtCore.QSize(100, 0))
        self.gridLayout_2 = QtWidgets.QGridLayout(course_add)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_course_id = QtWidgets.QLineEdit(course_add)
        self.lineEdit_course_id.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_course_id.setObjectName("lineEdit_course_id")
        self.gridLayout.addWidget(self.lineEdit_course_id, 4, 1, 1, 1)
        self.timeEdit_startTime = QtWidgets.QTimeEdit(course_add)
        self.timeEdit_startTime.setMinimumSize(QtCore.QSize(0, 30))
        self.timeEdit_startTime.setObjectName("timeEdit_startTime")
        self.gridLayout.addWidget(self.timeEdit_startTime, 5, 1, 1, 1)
        self.comboBox_weekDate = QtWidgets.QComboBox(course_add)
        self.comboBox_weekDate.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_weekDate.setObjectName("comboBox_weekDate")
        self.gridLayout.addWidget(self.comboBox_weekDate, 3, 1, 1, 1)
        self.timeEdit_endTime = QtWidgets.QTimeEdit(course_add)
        self.timeEdit_endTime.setMinimumSize(QtCore.QSize(0, 30))
        self.timeEdit_endTime.setObjectName("timeEdit_endTime")
        self.gridLayout.addWidget(self.timeEdit_endTime, 6, 1, 1, 1)
        self.comboBox_startWeeks = QtWidgets.QComboBox(course_add)
        self.comboBox_startWeeks.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_startWeeks.setObjectName("comboBox_startWeeks")
        self.gridLayout.addWidget(self.comboBox_startWeeks, 1, 1, 1, 1)
        self.comboBox_endWeeks = QtWidgets.QComboBox(course_add)
        self.comboBox_endWeeks.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_endWeeks.setObjectName("comboBox_endWeeks")
        self.gridLayout.addWidget(self.comboBox_endWeeks, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(course_add)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit_course_name = QtWidgets.QLineEdit(course_add)
        self.lineEdit_course_name.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_course_name.setObjectName("lineEdit_course_name")
        self.gridLayout.addWidget(self.lineEdit_course_name, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(course_add)
        self.label_7.setMinimumSize(QtCore.QSize(0, 30))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(course_add)
        self.label_8.setMinimumSize(QtCore.QSize(0, 30))
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(course_add)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(course_add)
        self.label_9.setMinimumSize(QtCore.QSize(0, 30))
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(course_add)
        self.label_6.setMinimumSize(QtCore.QSize(0, 30))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(course_add)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 7)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 1, 1, 1, 1)
        self.pushButton_register = QtWidgets.QPushButton(course_add)
        self.pushButton_register.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_register.setObjectName("pushButton_register")
        self.gridLayout_2.addWidget(self.pushButton_register, 2, 1, 1, 1)

        self.retranslateUi(course_add)
        self.pushButton_register.clicked['bool'].connect(course_add.button_register)
        QtCore.QMetaObject.connectSlotsByName(course_add)

    def retranslateUi(self, course_add):
        _translate = QtCore.QCoreApplication.translate
        course_add.setWindowTitle(_translate("course_add", "添加课程"))
        self.label_3.setText(_translate("course_add", "课程名称："))
        self.label_7.setText(_translate("course_add", "开始周数："))
        self.label_8.setText(_translate("course_add", "结束周数："))
        self.label_2.setText(_translate("course_add", "上课星期日："))
        self.label_9.setText(_translate("course_add", "课程编号："))
        self.label_6.setText(_translate("course_add", "开始时间："))
        self.label.setText(_translate("course_add", "结束时间："))
        self.pushButton_register.setText(_translate("course_add", "注册"))

