# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_course_add.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_course_add(object):
    def setupUi(self, course_add):
        course_add.setObjectName("course_add")
        course_add.resize(364, 338)
        course_add.setMinimumSize(QtCore.QSize(100, 0))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(course_add)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(course_add)
        self.label_3.setMinimumSize(QtCore.QSize(0, 20))
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_7 = QtWidgets.QLabel(course_add)
        self.label_7.setMinimumSize(QtCore.QSize(0, 20))
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(course_add)
        self.label_8.setMinimumSize(QtCore.QSize(0, 20))
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(course_add)
        self.label_9.setMinimumSize(QtCore.QSize(0, 20))
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_6 = QtWidgets.QLabel(course_add)
        self.label_6.setMinimumSize(QtCore.QSize(0, 20))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout.setStretch(5, 2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_course_name = QtWidgets.QLineEdit(course_add)
        self.lineEdit_course_name.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_course_name.setObjectName("lineEdit_course_name")
        self.verticalLayout_2.addWidget(self.lineEdit_course_name)
        self.dateEdit_startdate = QtWidgets.QDateEdit(course_add)
        self.dateEdit_startdate.setMinimumSize(QtCore.QSize(0, 30))
        self.dateEdit_startdate.setObjectName("dateEdit_startdate")
        self.verticalLayout_2.addWidget(self.dateEdit_startdate)
        self.comboBox_weeks = QtWidgets.QComboBox(course_add)
        self.comboBox_weeks.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_weeks.setObjectName("comboBox_weeks")
        self.verticalLayout_2.addWidget(self.comboBox_weeks)
        self.lineEdit_course_id = QtWidgets.QLineEdit(course_add)
        self.lineEdit_course_id.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_course_id.setObjectName("lineEdit_course_id")
        self.verticalLayout_2.addWidget(self.lineEdit_course_id)
        self.comboBox_time1 = QtWidgets.QComboBox(course_add)
        self.comboBox_time1.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_time1.setObjectName("comboBox_time1")
        self.verticalLayout_2.addWidget(self.comboBox_time1)
        self.comboBox_time2 = QtWidgets.QComboBox(course_add)
        self.comboBox_time2.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_time2.setObjectName("comboBox_time2")
        self.verticalLayout_2.addWidget(self.comboBox_time2)
        self.comboBox_time3 = QtWidgets.QComboBox(course_add)
        self.comboBox_time3.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_time3.setObjectName("comboBox_time3")
        self.verticalLayout_2.addWidget(self.comboBox_time3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButton_register = QtWidgets.QPushButton(course_add)
        self.pushButton_register.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_register.setObjectName("pushButton_register")
        self.horizontalLayout_2.addWidget(self.pushButton_register)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 2)
        self.verticalLayout_3.setStretch(2, 1)

        self.retranslateUi(course_add)
        self.pushButton_register.clicked['bool'].connect(course_add.button_register)
        QtCore.QMetaObject.connectSlotsByName(course_add)

    def retranslateUi(self, course_add):
        _translate = QtCore.QCoreApplication.translate
        course_add.setWindowTitle(_translate("course_add", "添加课程"))
        self.label_3.setText(_translate("course_add", "课程名:"))
        self.label_7.setText(_translate("course_add", "开始日期:"))
        self.label_8.setText(_translate("course_add", "持续周数:"))
        self.label_9.setText(_translate("course_add", "课程编号:"))
        self.label_6.setText(_translate("course_add", "课程时间:"))
        self.pushButton_register.setText(_translate("course_add", "注册"))

