# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_student_register.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_student_register(object):
    def setupUi(self, student_register):
        student_register.setObjectName("student_register")
        student_register.resize(680, 427)
        student_register.setStyleSheet("")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(student_register)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(student_register)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(1, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setMinimumSize(QtCore.QSize(0, 30))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setMinimumSize(QtCore.QSize(0, 30))
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setMinimumSize(QtCore.QSize(0, 30))
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setMinimumSize(QtCore.QSize(0, 30))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setMinimumSize(QtCore.QSize(0, 30))
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit_student_name = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_student_name.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_student_name.setObjectName("lineEdit_student_name")
        self.verticalLayout_4.addWidget(self.lineEdit_student_name)
        self.lineEdit_student_number = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_student_number.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_student_number.setObjectName("lineEdit_student_number")
        self.verticalLayout_4.addWidget(self.lineEdit_student_number)
        self.lineEdit_student_IdCard = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_student_IdCard.setEnabled(True)
        self.lineEdit_student_IdCard.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_student_IdCard.setObjectName("lineEdit_student_IdCard")
        self.verticalLayout_4.addWidget(self.lineEdit_student_IdCard)
        self.comboBox_permission = QtWidgets.QComboBox(self.widget)
        self.comboBox_permission.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_permission.setObjectName("comboBox_permission")
        self.verticalLayout_4.addWidget(self.comboBox_permission)
        self.comboBox_team = QtWidgets.QComboBox(self.widget)
        self.comboBox_team.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_team.setObjectName("comboBox_team")
        self.verticalLayout_4.addWidget(self.comboBox_team)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 108, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.pushButton_register = QtWidgets.QPushButton(self.widget)
        self.pushButton_register.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_register.setStyleSheet("")
        self.pushButton_register.setObjectName("pushButton_register")
        self.verticalLayout_5.addWidget(self.pushButton_register)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 1)
        self.verticalLayout_5.setStretch(2, 2)
        self.horizontalLayout_2.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(student_register)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableWidget_class_check = QtWidgets.QTableWidget(self.widget_2)
        self.tableWidget_class_check.setObjectName("tableWidget_class_check")
        self.tableWidget_class_check.setColumnCount(0)
        self.tableWidget_class_check.setRowCount(0)
        self.verticalLayout_6.addWidget(self.tableWidget_class_check)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)

        self.retranslateUi(student_register)
        self.pushButton_register.clicked['bool'].connect(student_register.register)
        QtCore.QMetaObject.connectSlotsByName(student_register)

    def retranslateUi(self, student_register):
        _translate = QtCore.QCoreApplication.translate
        student_register.setWindowTitle(_translate("student_register", "Form"))
        self.label_6.setText(_translate("student_register", "学生："))
        self.label_7.setText(_translate("student_register", "学号："))
        self.label_8.setText(_translate("student_register", "卡号："))
        self.label_10.setText(_translate("student_register", "权限："))
        self.label_9.setText(_translate("student_register", "团队："))
        self.pushButton_register.setText(_translate("student_register", "点击注册"))

