# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_student_swipe.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Stu_Swipe(object):
    def setupUi(self, Stu_Swipe):
        Stu_Swipe.setObjectName("Stu_Swipe")
        Stu_Swipe.resize(574, 452)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Stu_Swipe)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 531, 421))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.textBrowser = QtWidgets.QTextBrowser(self.horizontalLayoutWidget_2)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_3.addWidget(self.textBrowser)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 9)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_6.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setMinimumSize(QtCore.QSize(0, 20))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setMinimumSize(QtCore.QSize(0, 20))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEd_stuID = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEd_stuID.setEnabled(True)
        self.lineEd_stuID.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEd_stuID.setObjectName("lineEd_stuID")
        self.verticalLayout_2.addWidget(self.lineEd_stuID)
        self.comboBox_team = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_team.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_team.setMaximumSize(QtCore.QSize(16777215, 25))
        self.comboBox_team.setObjectName("comboBox_team")
        self.verticalLayout_2.addWidget(self.comboBox_team)
        self.dateEdit_starttime = QtWidgets.QDateEdit(self.horizontalLayoutWidget_2)
        self.dateEdit_starttime.setMinimumSize(QtCore.QSize(0, 25))
        self.dateEdit_starttime.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 10, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_starttime.setObjectName("dateEdit_starttime")
        self.verticalLayout_2.addWidget(self.dateEdit_starttime)
        self.dateEdit_endtime = QtWidgets.QDateEdit(self.horizontalLayoutWidget_2)
        self.dateEdit_endtime.setMinimumSize(QtCore.QSize(0, 25))
        self.dateEdit_endtime.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 10, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_endtime.setObjectName("dateEdit_endtime")
        self.verticalLayout_2.addWidget(self.dateEdit_endtime)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.pushButton_extract = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_extract.setObjectName("pushButton_extract")
        self.verticalLayout_5.addWidget(self.pushButton_extract)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.verticalLayout_5.setStretch(0, 5)
        self.verticalLayout_5.setStretch(1, 2)
        self.verticalLayout_5.setStretch(2, 1)
        self.verticalLayout_5.setStretch(3, 2)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 9)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)

        self.retranslateUi(Stu_Swipe)
        QtCore.QMetaObject.connectSlotsByName(Stu_Swipe)

    def retranslateUi(self, Stu_Swipe):
        _translate = QtCore.QCoreApplication.translate
        Stu_Swipe.setWindowTitle(_translate("Stu_Swipe", "Form"))
        self.label.setText(_translate("Stu_Swipe", "考勤记录"))
        self.label_6.setText(_translate("Stu_Swipe", "记录提取"))
        self.label_4.setText(_translate("Stu_Swipe", "学号："))
        self.label_5.setText(_translate("Stu_Swipe", "负责人："))
        self.label_2.setText(_translate("Stu_Swipe", "起始时间"))
        self.label_3.setText(_translate("Stu_Swipe", "截止时间"))
        self.pushButton_extract.setText(_translate("Stu_Swipe", "提取至excel"))

